### ISSUE TITLE
[Bug Report] reload不刷新Access Token

### ISSUE THREAD

**Issue by fred913** [jie65535/gc-openchat-plugin#2]
当`/serverchat reload`时，不会从配置文件刷新Access Token。
看了一下代码，问题在`MiniOneBotWsServer`校验token时，是从其成员token读取的AT，但是reload时又是在config对象里写入的token信息，没有同步到前者。
估计这个修好就解决问题了？

**Comment by fred913** [comment]
好家伙，光速修复

**Comment by jie65535** [comment]
希望协助测试一下 [openchat-dev-0.2.1.jar.zip](https://github.com/jie65535/gc-openchat-plugin/files/11185446/openchat-dev-0.2.1.jar.zip)
